### ISSUE TITLE
mat.at(i,j)[n] error

### ISSUE THREAD

**Issue by chloelle** [davidstutz/vlfeat-slic-example#1]
Great code - very helpful to somebody such as myself who wants to run the EPFL code without needing Visual Studio! Thank you - saved me much time! One comment: not sure if it's an issue of the OpenCV version, but the lines using syntax mat.at(i,j)[n] with n =0,1,2 give me an error - it looks like OpenCV wants me to use mat.at<Vec3b>(i, j) to get the individual channel values. Admittedly I'm new to OpenCV, but your code wouldn't compile using OpenCV 2.4.9. I'm using Eclipse CDT on Windows / MinGW for gcc, with OpenCV 2.4.9 built from source and VLFeat pre-build binaries.

**Comment by davidstutz** [comment]
Sorry for the late reply. I did not come across this problem previously when working with 2.4.8 and 2.4.11 (at least as far as I remember the versions). What is the exact compile error?

**Comment by chloelle** [comment]
Wow this was an old comment. not sure what the compile error was, but I went through my code and found that I'd changed lines 16-24 of your code to the following: 

```
float* image = new float[mat.rows*mat.cols*mat.channels()];
    for (int i = 0; i < mat.rows; ++i) {
        for (int j = 0; j < mat.cols; ++j) {
            Vec3b intensity = mat.at<Vec3b>(i, j);
            uchar blue = intensity.val[0];
            uchar green = intensity.val[1];
            uchar red = intensity.val[2];
            image[j + mat.cols*i + mat.cols*mat.rows*0] = float(blue);
            image[j + mat.cols*i + mat.cols*mat.rows*1] = float(green);
            image[j + mat.cols*i + mat.cols*mat.rows*2] = float(red);
        }
    }
```

and everything worked fine. Not sure if that version of OpenCV required you to access Vec3b values with the .val[n] or if it was just that you were missing the explicit cast of the uchar data to floats to put into float\* image.

**Comment by njustzsm** [comment]
hello，I download your code，but the dictionary named lib_vlfeat is empty,can your upload the files? thank you very much

**Comment by boltcoder** [comment]
> hello，I download your code，but the dictionary named lib_vlfeat is empty,can your upload the files? thank you very much

It's a git submodule. You should run 
`git submodule init`
`git submodule update` and it'll clone the library code in there

**Comment by davidstutz** [comment]
@boltcoder is right, just clone recursively to get the right vlfeat version.
